# data

In [9]:
from src.dataset import *

In [10]:
dataset_names = ['breast_cancer', 'heart_disease', 'diabetes']

In [11]:
for dn in dataset_names:
    print(f"Loading {dn} dataset...")
    dataset = Dataset(dn, cfg="config/datasets.yaml").run()
    print(f"Dataset {dn} loaded, preprocessed and saved successfully.\n")

Loading breast_cancer dataset...
Dataset breast_cancer loaded, preprocessed and saved successfully.

Loading heart_disease dataset...
Dataset heart_disease loaded, preprocessed and saved successfully.

Loading diabetes dataset...
Dataset diabetes loaded, preprocessed and saved successfully.

# models

In [4]:
from src.models import *

In [5]:
logreg_diabetes = Model("logistic_regression", cfg="config/models.yaml").run(dataset_name="diabetes")
logreg_heart_disease = Model("logistic_regression", cfg="config/models.yaml").run(dataset_name="heart_disease")
logreg_breast_cancer = Model("logistic_regression", cfg="config/models.yaml").run(dataset_name="breast_cancer")

In [6]:
randfor_diabetes = Model("random_forest", cfg="config/models.yaml").run(dataset_name="diabetes")
randfor_heart_disease = Model("random_forest", cfg="config/models.yaml").run(dataset_name="heart_disease")
randfor_breast_cancer = Model("random_forest", cfg="config/models.yaml").run(dataset_name="breast_cancer")

In [7]:
xgboost_diabetes = Model("xgboost", cfg="config/models.yaml").run(dataset_name="diabetes")
xgboost_heart_disease = Model("xgboost", cfg="config/models.yaml").run(dataset_name="heart_disease")
xgboost_breast_cancer = Model("xgboost", cfg="config/models.yaml").run(dataset_name="breast_cancer")

In [8]:
svm_diabetes = Model("svm", cfg="config/models.yaml").run(dataset_name="diabetes")
svm_heart_disease = Model("svm", cfg="config/models.yaml").run(dataset_name="heart_disease")
svm_breast_cancer = Model("svm", cfg="config/models.yaml").run(dataset_name="breast_cancer")

In [9]:
mlp_diabetes = Model("mlp", cfg="config/models.yaml").run(dataset_name="diabetes")
mlp_heart_disease = Model("mlp", cfg="config/models.yaml").run(dataset_name="heart_disease")
mlp_breast_cancer = Model("mlp", cfg="config/models.yaml").run(dataset_name="breast_cancer")

c:\00_work\projects\syn-vs-enc-simplified\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\00_work\projects\syn-vs-enc-simplified\.venv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

## model loading

In [10]:
from src.models import *

In [11]:
model = Model.load("models\logistic_regression__breast_cancer.joblib")

In [15]:
model.X_train.head()

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,mean_fractal_dimension,...,worst_radius,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension
546,-1.081325,-0.684076,-1.098091,-0.938523,-0.143774,-1.030979,-0.987817,-1.120082,0.267911,-0.111652,...,-1.039387,-0.636267,-1.076496,-0.871368,-0.169583,-1.055006,-1.095507,-1.382518,-0.355517,-0.551710
432,1.719055,0.058258,1.723026,1.692556,1.205523,0.844459,1.563102,1.985643,-0.319891,-0.321457,...,1.192963,-0.098883,1.153867,1.051965,1.496181,0.254042,1.240695,1.563677,0.212324,-0.177099
174,-0.984760,-0.963324,-1.008296,-0.868274,-0.600656,-1.162123,-1.114873,-1.261820,0.424902,-0.432030,...,-0.979333,-1.054776,-1.014542,-0.830233,-1.085753,-1.185478,-1.305831,-1.745063,-0.308601,-1.236095
221,-0.161119,-1.254207,-0.139183,-0.266177,0.621966,0.281600,-0.128052,-0.113729,0.549034,0.032944,...,-0.266969,-1.391862,-0.183517,-0.341005,0.229323,0.098824,-0.069509,-0.360965,0.265711,-0.120575
289,-0.783110,-0.093001,-0.815526,-0.736307,-0.656877,-1.028326,-0.813679,-0.701316,0.735232,-0.460382,...,-0.809525,0.075360,-0.833146,-0.740579,-0.901643,-0.999916,-0.944625,-0.800557,0.592503,-0.776144

# synthetic

In [1]:
from src.synthesizers import *

In [2]:
synth = Synthesizer("gaussian_copula", cfg="config/synthesizers.yaml")

In [3]:
synth.fit("breast_cancer")

c:\00_work\projects\syn-vs-enc-simplified\.venv\Lib\site-packages\sdv\single_table\base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

In [4]:
synth.save()

In [6]:
synth.sample()

,mean_radius,mean_texture,mean_perimeter,mean_area,mean_smoothness,mean_compactness,mean_concavity,mean_concave_points,mean_symmetry,mean_fractal_dimension,...,worst_texture,worst_perimeter,worst_area,worst_smoothness,worst_compactness,worst_concavity,worst_concave_points,worst_symmetry,worst_fractal_dimension,malignant
0,1.403071,0.786797,1.370419,1.241153,0.001894,0.743332,0.453848,0.613696,-0.241801,-0.373187,...,0.477781,1.194673,0.985843,-0.977830,0.471162,0.350213,1.013251,-0.016827,-0.399496,0
1,-0.252269,-0.603581,-0.258369,-0.344301,0.420196,0.224023,0.244431,0.152687,1.434313,0.647623,...,-1.428456,-0.599490,-0.543240,-0.202338,-0.562113,-0.389628,-0.666367,0.048690,-0.273115,1
2,-1.811109,-0.927215,-1.762545,-1.454443,1.161880,0.191183,0.000250,-0.353944,0.496864,2.162216,...,-1.072013,-1.534893,-1.222423,1.075285,0.277570,0.541582,0.036143,0.643891,1.495155,1
3,-0.099067,-0.442770,-0.009693,-0.412584,0.936458,1.580431,1.075520,1.071483,1.361546,1.341531,...,0.273120,0.119600,-0.235905,0.798219,1.283724,1.520387,1.198166,1.253914,1.639616,0
4,0.775502,-0.857532,0.602086,0.605009,-3.112085,-1.610136,-1.114873,-1.069720,-1.849182,-1.819865,...,-1.377432,0.305612,0.128353,-2.682695,-1.443878,-1.305831,-1.511414,-0.836854,-1.601839,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,0.087977,-1.091737,-0.001383,0.034813,-1.032267,-1.170832,-1.069219,-0.693707,-0.945146,-1.087930,...,-0.931624,-0.092073,-0.170576,-0.635952,-0.872937,-0.789499,-0.061617,-0.651110,-0.659027,0
565,-0.172597,-0.172052,-0.260560,-0.145268,-1.352512,-1.357717,-0.643272,-0.964465,-0.625458,-1.296454,...,-0.097419,-0.473708,-0.368376,-0.702640,-1.140188,-0.465758,-0.678542,-1.266692,-0.689687,1
566,-0.907579,0.331569,-1.025397,-0.869559,-1.844061,-1.610136,-1.114873,-1.261820,-0.432244,-0.975775,...,0.080541,-0.832966,-0.648215,-0.841825,-0.902447,-0.860189,-1.248176,-0.490054,-0.373305,1
567,0.593241,0.821372,0.437833,0.548526,-2.123407,-1.610136,-1.114873,-0.879335,-1.283796,-1.819865,...,0.240459,0.233032,0.390527,-2.229967,-1.443878,-1.305831,-1.093654,-1.273522,-1.601839,1
568,-0.975743,-0.456048,-1.034892,-0.835113,-1.274420,-1.537399,-0.902886,-0.861392,-0.669741,-0.859987,...,-0.910662,-1.023596,-0.663004,-0.883710,-1.423760,-0.793786,-0.735379,-1.208219,-1.601839,1

In [7]:
synth.run("diabetes")
synth.run("breast_cancer")
synth.run("heart_disease")

c:\00_work\projects\syn-vs-enc-simplified\.venv\Lib\site-packages\sdv\single_table\base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(
c:\00_work\projects\syn-vs-enc-simplified\.venv\Lib\site-packages\sdv\single_table\base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(
c:\00_work\projects\syn-vs-enc-simplified\.venv\Lib\site-packages\sdv\single_table\base.py:134: UserWarning: We strongly recommend saving the metadata using 'save_to_json' for replicability in future SDV versions.
  warnings.warn(

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,-0.027622,0.686202,0.456119,1.303774,0.922083,0.334001,1.008767,-0.627969,-0.696631,1.254047,0.675157,0.849196,-0.170810,1
1,-0.071048,0.271162,0.877985,0.671534,-0.783844,0.590052,0.573134,1.728524,-0.696631,-0.437793,-0.373877,-0.120397,-0.531729,0
2,-1.275893,-0.083808,0.877985,-0.439559,0.455408,-0.417635,-0.626311,0.615617,1.207599,1.427771,-0.660692,-0.626638,0.650146,0
3,0.958190,-0.760191,-0.122113,0.357272,1.067592,0.203199,1.016684,0.782985,0.017182,-0.318911,0.025004,-0.065545,-0.890238,0
4,-0.205729,-1.142794,-0.578416,-0.334881,-2.177907,-0.417635,-0.043385,0.032894,-0.626630,-0.087950,0.060043,-0.586914,-0.890238,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,1.919246,-0.125650,0.265830,1.600026,0.881508,1.381596,0.486165,-0.708251,1.143254,-0.435196,-0.377359,-0.201713,1.176752,0
299,-0.410037,-1.457296,-0.508974,0.900497,-0.684056,1.098316,-0.308226,1.023987,-0.696631,0.287710,1.463945,-0.417712,-0.890238,0
300,-0.037505,0.328571,0.750150,0.075972,1.297112,0.633579,0.428090,-0.716209,1.435481,-0.767388,0.207293,1.087188,-0.190158,1
301,-0.769598,0.686202,-0.127959,-1.305109,0.655281,-0.417635,1.016684,0.026815,1.107570,0.033804,-0.194361,0.655399,0.997220,1
302,-0.298742,0.222050,0.723866,0.597750,-0.298628,-0.417635,1.016684,0.035760,0.981830,0.359091,-0.835373,-0.711131,-0.153424,1